// ============================================================================
// bridge_execution.h — Bridge Execution Interface for .nvm ↔ .nvi/.nvw
// ============================================================================
//
// Standardizes how the Full-Stack Interpreter (.nvi) loads compiled .wasm modules
// generated by the Backend Compiler (.nvm) and surfaces them as plain function calls
// to the Frontend Interpreter (.nvw).
//
// This enables:
//   - .nvm compiled libraries to be loaded from .nvi interpreter
//   - .wasm modules to be surfaced as native function calls in .nvw
//   - Consistent ABI across all three ecosystem compilers
//
// ============================================================================

#pragma once

#include <string>
#include <vector>
#include <memory>
#include <unordered_map>
#include <variant>
#include <cstdint>

namespace novium {

// ============================================================================
// Wasm Module Load Result
// ============================================================================

struct WasmModuleLoadResult {
    bool success;                    // Whether loading succeeded
    std::string error_message;       // Error if unsuccessful
    std::string module_name;         // Name of loaded module
    std::vector<std::string> exported_functions; // List of exported function names
    std::vector<std::pair<std::string, std::string>> function_signatures; // name -> signature
    size_t memory_pages;             // Required WASM memory pages
};

// ============================================================================
// Wasm Module Interface
// ============================================================================

// Interface for loading and interacting with WASM modules
class WasmModuleInterface {
public:
    virtual ~WasmModuleInterface() = default;

    // Load a WASM module from binary data
    virtual WasmModuleLoadResult load(const std::vector<uint8_t>& wasm_data) = 0;

    // Load a WASM module from file path
    virtual WasmModuleLoadResult load_from_file(const std::string& file_path) = 0;

    // Call an exported function from the WASM module
    // Returns the result as a variant of common types
    virtual std::variant<long long, double, std::string, bool> call_function(
        const std::string& function_name,
        const std::vector<std::variant<long long, double, std::string, bool>>& args) = 0;

    // Get function signature
    virtual std::string get_function_signature(const std::string& function_name) = 0;

    // Get exported function names
    virtual std::vector<std::string> get_exported_functions() = 0;

    // Get module memory size in pages
    virtual size_t get_memory_pages() = 0;

    // Export a Novium function to the WASM module
    virtual bool export_function(
        const std::string& novium_function_name,
        const std::string& wasm_function_signature) = 0;

    // Set a Novium global variable from WASM memory
    virtual bool set_global(const std::string& name, const std::variant<long long, double, std::string, bool>& value) = 0;

    // Get a Novium global variable from WASM memory
    virtual std::variant<long long, double, std::string, bool> get_global(
        const std::string& name) = 0;
};

// ============================================================================
// Concrete Implementations
// ============================================================================

// WasmModule for .nvi interpreter - loads and executes WASM modules
class WasmModuleNVI : public WasmModuleInterface {
public:
    WasmModuleLoadResult load(const std::vector<uint8_t>& wasm_data) override;
    WasmModuleLoadResult load_from_file(const std::string& file_path) override;
    std::variant<long long, double, std::string, bool> call_function(
        const std::string& function_name,
        const std::vector<std::variant<long long, double, std::string, bool>>& args) override;
    std::string get_function_signature(const std::string& function_name) override;
    std::vector<std::string> get_exported_functions() override;
    size_t get_memory_pages() override;
    bool export_function(
        const std::string& novium_function_name,
        const std::string& wasm_function_signature) override;
    bool set_global(const std::string& name,
                  const std::variant<long long, double, std::string, bool>& value) override;
    std::variant<long long, double, std::string, bool> get_global(
        const std::string& name) override;
};

// WasmModule for .nvw frontend - surfaces WASM as native function calls
class WasmModuleNVW : public WasmModuleInterface {
public:
    WasmModuleLoadResult load(const std::vector<uint8_t>& wasm_data) override;
    WasmModuleLoadResult load_from_file(const std::string& file_path) override;
    std::variant<long long, double, std::string, bool> call_function(
        const std::string& function_name,
        const std::vector<std::variant<long long, double, std::string, bool>>& args) override;
    std::string get_function_signature(const std::string& function_name) override;
    std::vector<std::string> get_exported_functions() override;
    size_t get_memory_pages() override;
    bool export_function(
        const std::string& novium_function_name,
        const std::string& wasm_function_signature) override;
    bool set_global(const std::string& name,
                  const std::variant<long long, double, std::string, bool>& value) override;
    std::variant<long long, double, std::string, bool> get_global(
        const std::string& name) override;
};

// ============================================================================
// Bridge Execution Functions
// ============================================================================

// Load WASM module in .nvi interpreter and make functions available
bool bridge_load_wasm_in_nvi(
    const std::vector<uint8_t>& wasm_data,
    std::unordered_map<std::string, std::variant<long long, double, std::string, bool>>& globals);

// Call WASM function from .nvi and return result
std::variant<long long, double, std::string, bool> bridge_call_wasm_function(
    const std::string& function_name,
    const std::vector<std::variant<long long, double, std::string, bool>>& args);

// Surface WASM module as native function calls in .nvw frontend
// Returns function wrappers that can be called directly
std::vector<std::string> bridge_surface_wasm_in_nvw(
    const std::vector<uint8_t>& wasm_data,
    const std::unordered_map<std::string, std::string>& name_mapping);

// ============================================================================
// ABI Convention Standards
// ============================================================================

// Standard calling convention for cross-language function calls
struct CallConvention {
    // Calling convention: cdecl, stdcall, thiscall, fastcall
    std::string calling_convention;  // e.g., "cdecl"
    
    // Name mangling scheme
    std::string name_mangling;  // e.g., "none", "ms", "golang"
    
    // Argument passing convention
    // 0 = registers, 1 = stack, 2 = hybrid
    int arg_passing;  
    
    // Return value convention
    // 0 = register, 1 = stack, 2 = hidden pointer
    int return_passing;
    
    // Alignment requirement
    size_t alignment;
};

// Standard ABI for Novium ↔ WASM interop
inline CallConvention NOVIUM_WASM_ABI = {
    .calling_convention = "cdecl",
    .name_mangling = "none",
    .arg_passing = 0,  // registers
    .return_passing = 0,  // register
    .alignment = 8
};

// ============================================================================
// Execution Interface Factory
// ============================================================================

// Create bridge interface for specified target
std::unique_ptr<WasmModuleInterface> create_bridge_interface(
    const std::string& target);

// Create .nvi bridge interface
std::unique_ptr<WasmModuleInterface> create_nvi_bridge();

// Create .nvw bridge interface
std::unique_ptr<WasmModuleInterface> create_nvw_bridge();

// ============================================================================
// Example Usage Patterns
// ============================================================================

// Pattern 1: .nvm compiles to .wasm, .nvi loads and calls
/*
// In .nvm (compilation target):
fn external_computation(x: float, y: float) -> float:
    hardware_target = CUDA
    #pragma cuda kernel_name(matrix_mult)
    return matrix_mult(x, y)

// Compile: novium build matrix.nvm -o matrix.wasm

// In .nvi (runtime loading):
# Load the compiled WASM module
 bridge_load_wasm_in_nvi(wasm_data, globals)

# Call the exported function
let result = bridge_call_wasm_function("matrix_mult", [x, y])
print(result)

// Pattern 2: .nvm compiles to .wasm, .nvw surfaces as native calls
/*
// In .nvw (frontend web):
# Surface the WASM module
let fib_wrappers = bridge_surface_wasm_in_nvw(wasm_data, {
    "matrix_mult": "fibonacci"
})

# Now call as native Novium/web functions
let result = fib_wrappers["fibonacci"](x, y)
print(result)
*/