// ============================================================================
// codegen_stub.cpp — LLVM-free fallback implementation of LlvmCodeGen
// ============================================================================
//
// Compiled when NOVIUM_WITH_LLVM is OFF (the default) so the compiler builds
// without LLVM installed. Reports a clear error for --codegen/--header modes
// and generates a minimal C ABI header for --header.
//
// Enable real LLVM codegen:  cmake -DNOVIUM_WITH_LLVM=ON <src-dir>
//
// ============================================================================

#include "codegen.h"
#include "sema/types.h"

#include <iostream>
#include <fstream>

namespace novium {

LlvmCodeGen::LlvmCodeGen(const CodeGenConfig& config)
    : config_(config),
      result_() {}

CodeGenResult LlvmCodeGen::generate(const std::vector<std::unique_ptr<novium::Stmt>>& program) {
    (void)program;
    result_.error_message =
        "LLVM code generation is unavailable: the compiler was built without LLVM.\n"
        "  Rebuild with: cmake -DNOVIUM_WITH_LLVM=ON <source-dir>\n"
        "  (LLVM development libraries must be installed and found via find_package(LLVM))";
    result_.success = false;
    return std::move(result_);
}

bool LlvmCodeGen::generate_abi_header(const std::string& output_path) {
    std::ofstream header(output_path);
    if (!header.is_open()) {
        result_.error_message = "Could not open output file: " + output_path;
        return false;
    }

    header << "// ============================================================================\n"
           << "// novium.h — Generated C ABI header for Novium programs\n"
           << "// ============================================================================\n"
           << "//\n"
           << "// Generated by the Novium compiler (built without LLVM support).\n"
           << "// Numeric types map to fixed-width C types for ABI stability.\n"
           << "//\n"
           << "#pragma once\n"
           << "\n"
           << "#include <stdint.h>\n"
           << "#include <stdbool.h>\n"
           << "\n"
           << "#ifdef __cplusplus\n"
           << "extern \"C\" {\n"
           << "#endif\n"
           << "\n"
           << "typedef int64_t  novium_int;\n"
           << "typedef double   novium_float;\n"
           << "typedef bool     novium_bool;\n"
           << "typedef struct { const char* data; uint64_t len; } novium_string;\n"
           << "\n"
           << "#ifdef __cplusplus\n"
           << "}\n"
           << "#endif\n";

    return true;
}

} // namespace novium