# Novium SDK CMake Configuration
# Generated by `novium sdk` — do not edit by hand

set(NOVIUM_SDK_VERSION "0.1.5")
set(NOVIUM_SDK_PROFILE "debug")
set(NOVIUM_SDK_TARGET "native")

# Include paths
include_directories(
    "${CMAKE_CURRENT_SOURCE_DIR}/include"
    "${CMAKE_SOURCE_DIR}/src"
    "${CMAKE_SOURCE_DIR}/runtime"
)

# Library
add_library(novium-sdk STATIC
    src/sdk/novium.c
)

# Link runtime
target_link_libraries(novium-sdk
    novium_rt
)

# Install targets
install(TARGETS novium-sdk
    ARCHIVE DESTINATION lib
    LIBRARY DESTINATION bin
    RUNTIME DESTINATION bin)

# Package config
write basic-config
    prefix=@PACKAGE_PREFIX@
    exec_prefix=${prefix}
    libdir=${prefix}/lib
    includedir=${prefix}/include

    name=novium-sdk
    version=@PACKAGE_VERSION@

    # Cflags
    cflags=-I${prefix}/include

    # Libs
    libs=novium-sdk
    libs_static=novium-sdk

    # Requires
    requires=novium-runtime