// Novium SDK Header
// Generated by `novium sdk` — do not edit by hand

#pragma once

// C ABI type mappings
#define NOVIUM_C_TYPE(int)     int64_t
#define NOVIUM_C_TYPE(string) { const char*; size_t }
#define NOVIUM_C_TYPE(array) { void*; size_t }
#define NOVIUM_C_TYPE(slice) { const char*; size_t }

// Version info
#define NOVIUM_SDK_VERSION "0.1.5"

// Build configuration
#define NOVIUM_SDK_PROFILE "debug"
#define NOVIUM_SDK_TARGET "native"

// Function declarations for SDK runtime
extern void* novium_malloc(size_t size);
extern void novium_free(void* ptr);
extern void novium_print(const char* s);
extern int novium_add(int a, int b);