// Novium SDK Runtime Implementation
// Generated by `novium sdk`

#include "novium.h"
#include "runtime/novium_rt.h"

// Memory allocation
void* novium_malloc(size_t size) {
    return novium_runtime_malloc(size);
}

// Memory deallocation
void novium_free(void* ptr) {
    novium_runtime_free(ptr);
}

// Print function
void novium_print(const char* s) {
    // Output to stderr for SDK compatibility
    // In a full implementation, this would use the Novium runtime
    (void)s; // suppress unused parameter
}

// Simple addition
int novium_add(int a, int b) {
    return a + b;
}